import { ReactNode } from 'react';
import { AppMailProps, AppMailReplyProps, AppMailSidebarItem, ChartDataState, ChartOptionsState, CustomEvent, Demo, LayoutType, SortOrderType } from './demo';
import {
    AppBreadcrumbProps,
    AppConfigProps,
    AppMenuItem,
    AppMenuItemProps,
    AppTopbarRef,
    Breadcrumb,
    BreadcrumbItem,
    ChatContextProps,
    ClassArray,
    ClassDictionary,
    ClassValue,
    CSSTransitionProps,
    LayoutConfig,
    LayoutContextProps,
    LayoutState,
    MailContextProps,
    MenuContextProps,
    MenuModel,
    MenuProps,
    NodeRef,
    Page,
    TaskContextProps,
} from './layout';

type ChildContainerProps = {
    children: ReactNode;
};

export type {
    AppBreadcrumbProps,
    AppConfigProps,
    AppMailProps,
    AppMailReplyProps,
    AppMailSidebarItem,
    AppMenuItem,
    AppMenuItemProps,
    AppSearchProps,
    AppTopbarRef,
    Breadcrumb,
    Breadcrumb,
    BreadcrumbItem,
    ChartDataState,
    ChartOptionsState,
    ChatContextProps,
    ChildContainerProps,
    ClassArray,
    ClassDictionary,
    ClassValue,
    CSSTransitionProps,
    CustomEvent,
    Demo,
    LayoutConfig,
    LayoutContextProps,
    LayoutState,
    LayoutType,
    MailContextProps,
    MenuContextProps,
    MenuModel,
    MenuProps,
    NodeRef,
    Page,
    SearchableItem,
    SearchConfig,
    SortOrderType,
    TaskContextProps,
    TransitionProps,
    TransitionStatus,
};
